#!/bin/bash -x
set -o errexit

# Run fewer jobs on the Travis CI system.
CORES=8
test -n "$CI" && CORES=2

dumps=$(find dumps -name \*.dump)

#echo $dumps | xargs -P${CORES} -n1 -- ./fdxread --format raw 1>/dev/null
echo $dumps | xargs -P${CORES} -n1 -- ./fdxread --format nmea0183 1>/dev/null
#echo $dumps | xargs -P${CORES} -n1 -- ./fdxread --format json 1>/dev/null
#echo $dumps | xargs -P${CORES} -n1 -- ./fdxread --format signalk 1>/dev/null

